package com.bonussystem.common.tcp.enums;

public enum RequestType {

    LOGIN,
    REGISTER,

    GET_ALL_USERS,
    GET_USERS_BY_ROLE,
    UPDATE_USER,
    BLOCK_USER,
    UNBLOCK_USER,
    DELETE_USER,

    GET_ALL_EMPLOYEES,
    ADD_EMPLOYEE,
    UPDATE_EMPLOYEE,
    DELETE_EMPLOYEE,

    GET_ALL_DEPARTMENTS,
    ADD_DEPARTMENT,
    UPDATE_DEPARTMENT,
    DELETE_DEPARTMENT,

    GET_ALL_KPI_INDICATORS,
    ADD_KPI_INDICATOR,
    UPDATE_KPI_INDICATOR,
    DELETE_KPI_INDICATOR,

    GET_ALL_PERIODS,
    ADD_PERIOD,
    UPDATE_PERIOD,
    DELETE_PERIOD,

    GET_KPI_RESULTS_BY_DEPARTMENT,
    ADD_KPI_RESULT,
    UPDATE_KPI_RESULT,
    DELETE_KPI_RESULT,

    CALCULATE_BONUSES,
    GET_ALL_BONUS_CALCULATIONS,
    APPROVE_CALCULATION,
    REJECT_CALCULATION,

    GET_BONUS_CALCULATIONS_BY_DEPARTMENT,

    GET_BONUS_REPORT,
    GET_STATISTICS,

    UPDATE_PROFILE,

    GET_EMPLOYEES_BY_DEPARTMENT,
    GET_EMPLOYEE_BY_USER_ID
}